

#Spring相关配置
spring:
  #数据库配置
  datasource:
    url: jdbc:mysql://localhost:3306/DB_School_trade?serverTimezone=UTC&characterEncoding=UTF-8&useSSL=false&serverTimezone=GMT&allowPublicKeyRetrieval=true&useSSL=false
    username: root
    password: 123456
    driver-class-name: com.mysql.cj.jdbc.Driver
  #web文件限制配置
  servlet:
    multipart:
     enabled: true
     max-file-size: 200MB
     max-request-size: 200MB
  #Json配置
  jackson:
    time: GMT+8
    date-format: yyyy-MM-dd HH:mm:ss

#文件路径
baseUrl: http://localhost:8080
#C:/exam/xxx/pic
userFilePath: C:\Users\28389\Desktop\stb\pic

#Mybatis配置
mybatis:
  typeAliasesPackage: com.shanzhu.st.entity
  mapperLocations: classpath:mapper/*.xml